# Generated by Django 3.2.25 on 2024-06-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Nome')),
                ('government_id', models.IntegerField(verbose_name='Número do Documento')),
                ('email', models.EmailField(max_length=254, verbose_name='Email do Sacado')),
                ('debt_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('debt_due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('debt_id', models.UUIDField(unique=True, verbose_name='UUID para Débito')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('CONFIRMED', 'Confirmed')], default='PENDING', max_length=10)),
            ],
            options={
                'verbose_name': 'Boleto',
            },
        ),
    ]
